### ISSUE TITLE
Could not find executable pandoc-beamer-block error on windows

### ISSUE THREAD

**Issue by SALAH30** [chdemko/pandoc-beamer-block#1]
For windows I have this error:

```
Error running filter pandoc-beamer-block:
Could not find executable pandoc-beamer-block
```
I installed *pandoc* and the filter *pandoc-beamer-block*, and add the path to the environment variables on windows, but still the same error.
The path : *c:\python38\lib\site-packages*

**Comment by chdemko** [comment]
See https://github.com/sergiocorreia/panflute/issues/142
